spring:
  profiles:
    active: dev
#    数据库设置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dbgirl?useSSL=false&characterEncoding=utf8
    username: root
    password: chenhao
    type: com.alibaba.druid.pool.DruidDataSource



#    druid配置
#    devtools 热部署设置
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/**

#      thymeleaf 环境设置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    content-type: text/html
#mybatis 设置
mybatis:
  type-aliases-package: com.franklin.mars.domain
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:config/mybatis-config.xml
#日志存放位置
logging:
  file: ./log/my-log.log
#  分页设置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
#  服务器设置
server:
  session:
    timeout: 30

